apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: microservices
  labels:
    app: customer
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: customer