apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: microservices
  labels:
    app: customer
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: Customer
          image: customerImage
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8091
          env:
            - name: CS_PORT
              value: "8080"
            - name: CS_METRICS_PORT
              value: "8091"
            - name: KAFKA_CONSUMER_GROUP_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: customer-postgresql-pguser-customer
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: customer-postgresql-pguser-customer
                  key: port
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: customer-postgresql-pguser-customer
                  key: dbname
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: customer-postgresql-pguser-customer
                  key: user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-postgresql-pguser-customer
                  key: password
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: KafkaCustomerSecret
                  key: username
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: KafkaCustomerSecret
                  key: password
            - name: KAFKA_PORT
              value: "9093"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: "8091"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: "8091"
            initialDelaySeconds: 15
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8091
            failureThreshold: 12
            periodSeconds: 10