apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: customer-postgresql
  namespace: microservices
spec:
  postgresVersion: "16"
  instances:
    - name: customer-postgres
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
  users:
    - name: customer
      passwordSecret:
        name: postgres-secret
        key: POSTGRES_PASSWORD
      databases:
        - CustomerDb
      options: 'SUPERUSER'