apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: auth-postgresql
  namespace: microservices
spec:
  postgresVersion: "16"
  instances:
    - name: auth-postgres
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
  users:
    - name: authuser
      passwordSecret:
        name: postgres-secret
        key: POSTGRES_PASSWORD
      databases:
        - AuthenticationDb
      options: 'SUPERUSER'