apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-scrape-config
  namespace: monitoring
data:
  scrape.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      external_labels:
        cluster: kafka
    scrape_configs:
      - job_name: 'kafka-broker'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: [kafka]
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_strimzi_io_cluster]
            regex: kafka-cluster
            action: keep
          
          - source_labels: [__meta_kubernetes_pod_label_strimzi_io_nodepool]
            regex: broker
            action: keep
    
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: '$1:9404'
    
      - job_name: 'kafka-controller'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: [kafka]
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_strimzi_io_cluster]
            regex: kafka-cluster
            action: keep
      
          - source_labels: [__meta_kubernetes_pod_label_strimzi_io_nodepool]
            regex: controller
            action: keep
      
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: '$1:9404'
    
      - job_name: 'customer'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: [microservices]
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: customer
            action: keep
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: '$1:8091'
          - target_label: __metrics_path__
            replacement: /actuator/prometheus
